.include <sys.args.mk>
CFLAGS+= -nostdlibinc

LIBNAME= libm
SRCS= acos.c   bessel.c  catan.c   cimag.c     creal.c     erf.c            feconsts.c         fesetexceptflag.c  fmax.c        getsign.c  log1p.c   matherr.c    remainder.c  sincos.c \
acosh.c  cabs.c    catanh.c  clog.c      csin.c      exp2.c           fegetenv.c         fesetround.c       fmin.c        hypot.c    log2.c    modf.c       remquo.c     sinh.c \
asin.c   cacos.c   cbrt.c csinh.c     exp.c            fegetexceptflag.c  fetestexcept.c     fmod.c        ilogb.c    logb.c    nan.c        rint.c       sqrt.c \
asinh.c  cacosh.c  ccos.c    copysign.c  csqrt.c     expm1.c          fegetround.c       feupdateenv.c      fpclassify.c  ldexp.c    log.c     nearbyint.c  round.c      tan.c \
atan2.c  carg.c    ccosh.c   cosh.c      ctan.c      fabs.c           feholdexcept.c     float.c            frexp.c       llrint.c   lrint.c   nextafter.c  scalbn.c     tanh.c \
atan.c   casin.c   ceil.c    cpow.c      ctanh.c     fdim.c           feraiseexcept.c    floor.c            gamma.c       llround.c  lround.c  pow.c        setsign.c    trunc.c \
atanh.c  casinh.c  cexp.c    cproj.c     cxconsts.c  feclearexcept.c  fesetenv.c         fma.c log10.c signbit.c

.include <sys.lib.mk>
